### ISSUE TITLE
(checksum error) Proper use of onEnter hook in routes

### ISSUE THREAD

**Issue by MarufSarker** [denvned/isomorphic-relay-router#10]
Thank you for your amazing method for server-side rendering of Relay apps.

While testing your _todo exmaple_, I've removed all components and made only two components, 

``` javascript
// App.js
<div>
  <div>
    Main App
  </div>
  <div>
    {
      this.props.children
    }
  </div>
</div>
```

``` javascript
// RoutedAuthenticatedBody.js
<div>
  Routed Authenticated Body
</div>
```

and made all other necessary mutation, query changes. (done these just for simplicity).

All I wanted to see how to use **onEnter** hook in **routes.js**.

But, in <a href="https://github.com/denvned/isomorphic-relay-router/blob/master/examples/todo/src/routes.js" target="_blank">routes.js</a> using <a href="https://github.com/rackt/react-router/blob/master/docs/guides/basics/RouteConfiguration.md#enter-and-leave-hooks" target="_blank">onEnter</a> hook of 'react-router' seems a bit problematic. 

As the **routes.js** is being used by both **server** and **client** side, if I want to let any specific route to be accessed based on **user's authentication**, I have to let both server and client side acknowledge about the current authentication state. 

(_using cookies_)

On **server side** I can fairly easily detect and pass the current authentication state during **renderOnServer.js**'s **match({...** process and pass required values to **routes.js** via some function and let it know the **authentication state** and take proper action via some function to control **onEnter** hook. 

But for **client side** the data is coming after it's being passed only after the **res.render(...** on **renderOnServer.js** and let's say I'm passing that information using another global variable passing to **index.ejs** along with other variables, namely preloadedData, reactOutput. 

It's an asynchronous process, but let's say ignoring that fact, after receiving my authentication state using that extra variable from **index.ejs** I control the **onEnter** hook's behavior same as sever side, as did in **renderOnServer.js** (I don't know if it's necessary on not, but I tried both and they both produced my final issue). 

After all these, when I tried to enter the route which requires **onEnter** hook's action, I got a instant glance of the routed view and redirected to root view, and a _console.log_ on client side stating below,

``` javascript
Warning: React attempted to reuse markup in a container 
but the checksum was invalid. This generally means that 
you are using server rendering and the markup generated 
on the server was not what the client was expecting. 
React injected new markup to compensate which works but 
you have lost many of the benefits of server rendering. 
Instead, figure out why the markup being generated is 
different on the client or server:
 (client) d=".1t76dhvha0w.8"></div></div>
 (server) d=".1t76dhvha0w.8"><div data-reactid=".1
```

So, it seems the server is sending a react element but the client is producing a normal element.

Is there a way to solve this issue?

Thanks :)

**Comment by denvned** [comment]
Hi @MarufSarker, It's hard to tell what the problem might be not seeing your code. Does the client actually enter the route having `onEnter`? You can put a breakpoint in `onEnter` to check that.

**Comment by MarufSarker** [comment]
After further inspection, I realized that, the issue was my method of accessing the authorized route. 
I was accessing the route directly from address-bar, **while not persisting the authorized state**. 
So, after solving that, things seems to be working.

Closing the issue, while the checksum error was not the issue of your fairly straight and awesome implementation.

Thanks again :)
