### ISSUE TITLE
Stuck at Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite compo nents).

### ISSUE THREAD

**Issue by thelordoftheboards** [denvned/isomorphic-relay-router#11]
I attempted to upgrade to the latest versions of Relay 0.6.1 and the accompanying isomorphic-relay and isomorphic-relay-router. My code that performs the server rendering is here:

https://github.com/codefoundries/isomorphic-material-relay-starter-kit/blob/relay_0_6_1/webapp/renderOnServer.js

It is directly derived from the To Do example in this repository. It works with Relay 0.6.0 and the accompanying isomorphic libraries. Here is a shortened version where I removed code that is, I believe, not essential to this issue:

``` javascript
export default function renderOnServer( req, res, next, assetsPath )
{
  match( { routes, location: req.originalUrl }, ( error, redirectLocation, renderProps ) =>
    {
.......
      else if( renderProps )
      {
        console.log( "Before IsomorphicRouter.prepareData, renderProps=" + JSON.stringify( renderProps ) );
        IsomorphicRouter.prepareData( renderProps ).then( render, next );
      }
.......

      function render( data )
      {
.....
        console.log( 'Before ReactDOMServer.renderToString, renderProps=' + JSON.stringify( renderProps ) );
        const reactOutput = ReactDOMServer.renderToString(
            <IsomorphicRouter.RoutingContext {...renderProps} />
        );
        console.log( 'COMPLETE!' );

        res.render( path.resolve( __dirname, '..', 'webapp/views', 'index.ejs' ), {
            preloadedData: JSON.stringify(data),
            assetsPath: assetsPath,
            reactOutput,
            isomorphicVars: isoVars
        } );
      }
    }
  );
};

```

When I try to load up localhost:4444, I get the following in the log:

```
--------------------------------------------------------------------------------
isomorphic-material-relay-starter-kit 0.5.0 running as development
Serving at 127.0.0.1:4444
--------------------------------------------------------------------------------
Warning: [react-router] `props.history` and `context.history` are deprecated. Please use `context.router`. http://bit.ly/1mj4IZr
Before IsomorphicRouter.prepareData, renderProps={"routes":[{"path":"/","queries":{},"indexRoute":{"queries":{}}},{"queries":{}}],"params":{},"location":{"pathname
":"/","search":"","hash":"","state":null,"action":"POP","key":"ddmazx","query":{},"$searchBase":{"search":"","searchBase":""}},"components":[null,null],"history":{"__v2_compatible__":true},"router":{"__v2_compatible__":true}}
Warning: [react-router] `props.history` and `context.history` are deprecated. Please use `context.router`. http://bit.ly/1mj4IZr
Before ReactDOMServer.renderToString, renderProps={"routes":[{"path":"/","queries":{},"indexRoute":{"queries":{}}},{"queries":{}}],"params":{},"location":{"pathnam
e":"/","search":"","hash":"","state":null,"action":"POP","key":"ddmazx","query":{},"$searchBase":{"search":"","searchBase":""}},"components":[null,null],"history":{"__v2_compatible__":true},"router":{"__v2_compatible__":true}}
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).
```

I am not sure if the warning is critical. However, `ReactDOMServer.renderToString` does not like whatever it is being given.
It could be that I am doing something wrong, but given that I only upgraded the versions, I would hope I am not. I also looked at the code for the To Do example for any changes I would have to implement and I can't see anything obvious.

Any ideas for what should I look into next?

**Comment by denvned** [comment]
Hi @thelordoftheboards Yesterday I updated the ToDo example of isomorphic-relay-router to use Relay v0.6.1. Did you try to run it? Does it produce the same error?

**Comment by thelordoftheboards** [comment]
Not yet, I will try that tomorrow morning, it's already early in the AM here. I will post back the result.

**Comment by thelordoftheboards** [comment]
Having trouble running the ToDo, getting syntax errors. Might be something with my global packages. However, I have a specific question with that regard. In the readme.md it says:

```
npm install -g babel@5
Note that only babel v5 is currently supported.
```

However, in the package I am seeing:

```
    "babel-cli": "^6.3.17",
    "babel-core": "^6.3.26",
    "babel-plugin-transform-runtime": "^6.3.13",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-preset-stage-0": "^6.3.13",
    "babel-relay-plugin": "0.6.3",
```

Is the requirement to run babel 5 still valid? I am only asking in order to know if this is the problem I am facing, or not. The specific error I am getting is:

```
npm start

> @ prestart /Users/alex/Documents/_temp/isomorphic-relay-router-master/examples/todo
> npm run build


> @ build /Users/alex/Documents/_temp/isomorphic-relay-router-master/examples/todo
> npm run update-schema && babel --presets es2015,stage-0,react --plugins transform-runtime,./build/babelRelayPlugin src --out-dir lib && webpack



> @ update-schema /Users/alex/Documents/_temp/isomorphic-relay-router-master/examples/todo
> babel-node --presets es2015,stage-0 ./scripts/updateSchema.js

src/client.js -> lib/client.js
SyntaxError: src/components/Todo.js: A semicolon is required after a class property (35:3)
  33 |       })
  34 |     );
> 35 |   }
     |    ^
  36 |   _handleDestroyClick = () => {
  37 |     this._removeTodo();
  38 |   }
```

which does sound like it could be something related to babel. Advise?

**Comment by thelordoftheboards** [comment]
So, babel 5 or 6, I had to modify all the properties to have a ; in the end like this:

``` javascript
  _handleBlur = () => {
    if (this.props.commitOnBlur) {
      this._commitChanges();
    }
  };
```

After I did this the sample ran and was functional. I saw a warning below:

```
Warning: `Relay.Store.update` is deprecated. Please use `Relay.Store.commitUpdate` or `Relay.Store.applyUpdate` instead.
```

However it runs. I am closing this issue, there must be a separate problem related to the upgrade in my project. Sorry about the trouble.

**Comment by thelordoftheboards** [comment]
So,

``` javascript
<IsomorphicRouter.RoutingContext {...renderProps} />
```

became

``` javascript
<IsomorphicRouter.RouterContext {...renderProps} />
```

Yeah, that took me a while. I am just posting here in case someone else encounters the same.

**Comment by denvned** [comment]
> Is the requirement to run babel 5 still valid?

No, sorry for that. I have just fixed the readme.

Also I got rid of the warnings in the example.

**Comment by thelordoftheboards** [comment]
Thank you!

**Comment by fenos** [comment]
Hi @denvned Thanks a lots  for this library! :+1:  But i got a very similar issue while trying to setup the Isomorphic render.

The error that i get is the following:

```
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `IsomorphicRenderer`.
```

I have copied and follow at detail the example folder,  (which when cloned it worked), but on my current setup it throw that error and the page doesn't even render. I'm using babel-6 and all the required presets, Any help would be highly appreciated. (I'm excited to start my new Isomorphic project )

This is my `renderOnServer` middleware:

``` js
import Html from './helpers/Html';
import IsomorphicRouter from 'isomorphic-relay-router';
import path from 'path';
import React from 'react';
import ReactDOMServer from 'react-dom/server';
import Relay from 'react-relay';
import RelayStoreData from 'react-relay/lib/RelayStoreData';
import {match} from 'react-router';
import routes from './routes';

const GRAPHQL_URL = `http://localhost:8085/graphql`;

Relay.injectNetworkLayer(new Relay.DefaultNetworkLayer(GRAPHQL_URL));

RelayStoreData.getDefaultInstance().getChangeEmitter().injectBatchingStrategy(() => {
});

export default (req, res, next) => {
  match({ routes, location: req.originalUrl }, (error, redirectLocation, renderProps) => {
        if (error) {
          next(error);
        } else if (redirectLocation) {
          res.redirect(302, redirectLocation.pathname + redirectLocation.search);
        } else if (renderProps) {
          IsomorphicRouter.prepareData(renderProps).then(render, next);
        } else {
          res.status(404).send('Not Found');
        }

        function render(data) {
          const reactOutput = ReactDOMServer.renderToString(
              <IsomorphicRouter.RouterContext {...renderProps} />
          );
          res.send('<!doctype html>\n' +
              ReactDOM.renderToString(
                  <Html assets={webpackIsomorphicTools.assets()}
                        component={reactOutput}
                        preloadedData={JSON.stringify(data)}/>
              ));
        };
      }
  );
```

Note: My graphQL end point is listening on port 8085 while the isomorphic app would listen on port 8080,
not sure if it might be the issue

**Comment by fenos** [comment]
@denvned I realised few things in my current setup that was preventing this to work:

1 - I had `react-router` with a old version
2 - After i fix that still nothing was rendering but no errors, i wrap the `IsomorphicRoute.RouterContext` in a try catch and i had few wrong imports, after fix that everything worked :)

**Comment by denvned** [comment]
@fenos I'm glad you solved the issue. I also suggest you to replace the last `ReactDOM.renderToString` with `ReactDOMServer.renderToStaticMarkup`, otherwise React will not reuse  the markup on the client.
