### ISSUE TITLE
IsomorphicRootContainer: prop type `relayContext` is invalid

### ISSUE THREAD

**Issue by chrissm79** [denvned/isomorphic-relay-router#15]
I'm running into  some issues when I attempt to use isomorphic-relay-router w/ [universal-redux](https://github.com/bdefore/universal-redux). I created a [dummy app](https://github.com/chrissm79/universal-redux-relay) that's closely represents the issue I'm running into with my (private) application. When attempting to load a page w/ a Relay query ("http://localhost:3000/todo"), it just hangs. If I attempt to go to a route ("http://localhost:3000") without a relay query, I get:

`"IsomorphicRootContainer: prop type `relayContext` is invalid; it must be a function, usually from React.PropTypes. Check the render method of `RelayRouterContext`."`

If I remove the isomorphic-relay-router and instead just use relay on the client side, I can bring up the homepage and click on the link to go to the Todo app.

universal-redux does use redux and redux-async-connect which I attempted to remove, but still ran into the issue. Is there something wrong w/ my setup? Thanks!!

**Comment by denvned** [comment]
Thanks for report. It should be fixed in the just released version of _isomorphic-relay_. Can please update the packages and verify that it is fixed?

**Comment by chrissm79** [comment]
That does indeed get rid of the `relayContext` issue. However, on my personal app I now get:

``` bash
Warning: RelayContainer: Expected query `company` to be supplied to `Index` as a prop from the parent. Pass an explicit `null` if this is intentional.
[1] ERROR GENERATING ROOT COMPONENT:   Error: Invariant Violation: RelayQL: Unexpected invocation at runtime. Either   the Babel transform was not set up, or it failed to identify this call site. M  ake sure it is being used verbatim as `Relay.QL`.
```

Looking at my server (PHP), the graphql route never gets hit. It's a bit odd, because on the dummy app, after the update, the http://localhost:3000/todo route just hangs rather than throwing the error.

Personal App package.json

``` json
{
  "name": "myapp",
  "version": "0.0.1",
  "description": "MyApp",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/bdefore/universal-redux-starter.git"
  },
  "scripts": {
    "build": "universal-redux-build",
    "start": "NODE_ENV=production NODE_PATH=./src universal-redux-server",
    "dev-server": "NODE_PATH=./src universal-redux-server",
    "dev": "concurrent --kill-others \"npm run watch-client\" \"npm run dev-server\"",
    "watch-client": "universal-redux-watch"
  },
  "author": {
    "name": "Christopher Moore"
  },
  "license": "MIT",
  "dependencies": {
    "bootstrap-sass": "^3.3.6",
    "classnames": "^2.2.3",
    "font-awesome": "^4.5.0",
    "isomorphic-relay": "^0.5.3",
    "isomorphic-relay-router": "^0.6.2",
    "jquery": "^2.2.0",
    "lodash": "^4.5.0",
    "moment": "^2.11.2",
    "pickadate": "^3.5.6",
    "react-bootstrap": "^0.28.3",
    "react-document-meta": "^2.0.2",
    "react-relay": "^0.7.1",
    "react-router-relay": "^0.9.0",
    "redux-form": "^4.2.0",
    "serialize-javascript": "^1.1.2",
    "universal-redux": "3.0.0"
  },
  "devDependencies": {
    "babel-plugin-transform-es2015-classes": "^6.5.2",
    "babel-relay-plugin": "^0.7.1",
    "concurrently": "1.0.0",
    "react": "^0.14.6",
    "react-dom": "^0.14.6",
    "react-redux": "4.3.0",
    "react-router": "2.0.0",
    "react-router-redux": "3.0.0"
  }
}
```

**Comment by denvned** [comment]
> RelayQL: Unexpected invocation at runtime. Either the Babel transform was not set up, or it failed to identify this call site.

Most probably that is the cause. Make sure Babel actually runs _babelRelayPlugin_.

You can also try to tell Babel to run _babelRelayPlugin_ before other transforms:

``` json
  "passPerPreset": true,
  "presets": [
    {
      "plugins": [
        "./build/babelRelayPlugin"
      ]
    },
    "react",
    "es2015",
    "stage-0"
  ],
```

**Comment by chrissm79** [comment]
That was it! In addition, the ./bin/transpile.js was loading the .babelrc file from universal-redux and merging mine w/ webpack so it wasn't loading correctly on the server side. 

Thanks @denvned!!
