### ISSUE TITLE
Is downloading app.js before rendering

### ISSUE THREAD

**Issue by reactor81** [denvned/isomorphic-relay-router#16]
The app.js has gotten large (1.8MB) and is unminimized. Loading my domain first requires the user to download the app.js before anything appears. 

1 - Since this is isomorphic, isn't the rendering supposed to happen without waiting for app.js? 

2 - Any tips for how to minimize the app.js without causing any negative side effects?

**Comment by denvned** [comment]
1) Try to place your `script` tags at the end of `body`. Or use the `defer` attribute. See: http://stackoverflow.com/questions/436411/where-is-the-best-place-to-put-script-tags-in-html-markup

2) _isomorphic-relay_ does not impose any special restrictions on minimization, so usual methods should work.

**Comment by reactor81** [comment]
Interesting, @denvned  started to debug renderOnServer a bit. I removed app.js from index.ejs to try and get a server-side only output.. 

The 'reactOutput' variable in renderOnServer.js is only yielding "noscript data-reactid=".2b7qpahrv9c" data-react-checksum="-1176366733">/noscript>"

where could I look to debug this more?

**Comment by reactor81** [comment]
Interesting, seems to only be an issue with the index route. other routes are properly rendering on server.

**Comment by reactor81** [comment]
looks like there was an issue in my indexroute that was causing it to fail. (a relay issue). but for whatever reason it worked on client. 

anyhow, it seems okay now (fixed the relay query). thanks.
