### ISSUE TITLE
import IsomorphicRouter from 'isomorphic-relay-router'; fail

### ISSUE THREAD

**Issue by VictorienTardif** [denvned/isomorphic-relay-router#18]
/node_modules/react-relay/node_modules/fbjs/node_modules/whatwg-fetch/fetch.js:4
  if (self.fetch) {
      ^
ReferenceError: self is not defined

**Comment by thelordoftheboards** [comment]
Are you trying to run the ToDo example?

**Comment by VictorienTardif** [comment]
Well I never managed to run the todo example (a lot of errors with babel and babel-cli) so I tried to implement it my self line by line but I just can't import IsomorphicRouter without getting that error?

**Comment by thelordoftheboards** [comment]
Is your babel globally installed? Is it version 6?

**Comment by VictorienTardif** [comment]
Yes, I followed the steps, but what Im really interested on is not to run the todo example but to understand why import IsomorphicRouter is not working? Is it related to babel? Thanks

**Comment by thelordoftheboards** [comment]
I can not tell based on the information you provide, my only clue was that there was an issue with babel-cli when you ran the todo example.

**Comment by VictorienTardif** [comment]
Sorry, so, I just started from zero to retry to run the example. 
I first installed babel globally, then `npm install` and `npm start`. I don't have the same error now, I have an error:  `Error: The (relay-query) Babel 5 plugin is being run with Babel 6.`

Then, I tried to import IsomorphicRouter into my own project and doing that I have an error 

```
/node_modules/react-relay/node_modules/fbjs/node_modules/whatwg-fetch/fetch.js:4
if (self.fetch) {
^
ReferenceError: self is not defined
```

**Comment by thelordoftheboards** [comment]
I would suggest to double check at your babel configuration, I think there are big differences between 5 and 6. If it is possible in your case and would not affect the rest of your work, try globally uninstalling babel and then installing 6, and make sure in your package.json you are using babel 6 components, including the right versions for the babel plugins for Relay.

**Comment by denvned** [comment]
> I first installed babel globally, then npm install and npm start. I don't have the same error now, I have an error: Error: The (relay-query) Babel 5 plugin is being run with Babel 6.

That was fixed after I updated _babel-relay-plugin_ in the ToDo example.

> /node_modules/react-relay/node_modules/fbjs/node_modules/whatwg-fetch/fetch.js:4
> if (self.fetch) {

Probably you have outdated version of _react-relay_ in your project. Update to v0.7.3 if this is the case.
