### ISSUE TITLE
Current master broken?

### ISSUE THREAD

**Issue by reactor81** [denvned/isomorphic-relay-router#19]
npm start -->

Error: The (relay-query) Babel 5 plugin is being run with Babel 6.

---

npm list -g --depth=0
/Users/steve/.nvm/versions/node/v5.8.0/lib
├── babel-cli@6.6.5
├── babel-preset-es2015@6.6.0
├── babel-preset-react@6.5.0
├── babel-preset-stage-0@6.5.0
├── eslint@2.4.0
├── npm@3.7.3
├── react-native-cli@0.1.10
└── webpack@1.12.14

**Comment by denvned** [comment]
The issue was https://github.com/facebook/relay/issues/887 I've updated _babel-relay-plugin_ to v0.7.3, so now the example should work.
