### ISSUE TITLE
Unsupported .if on fragments when rendering on server side?

### ISSUE THREAD

**Issue by shaimo** [denvned/isomorphic-relay-router#21]
I have an app which is working fine when I do only client side rendering, and also when I do server side but I'm now running into a strange issue:
If I add to one of my relay components a conditional fragment with .if such as:

```
                ${Followers.getFragment('user').if(vars.isFollowers)}
```

This works perfectly ok if I don't do server side rendering. But on the server it stops working if isFollowers is true (either by default or by supplying it as a relay variable on the route). I see no error anywhere (client nor server). The prepareParams is getting called (a few times like always) and also prepareVariables is called (if it is defined). But the render function of the component itself never get called so the component is not rendered at all.
I rely heavily on these conditional directives, so currently can't really do SSR...
Any help would be greatly appreciated

**Comment by shaimo** [comment]
I'm trying to see exactly what causes the problem. Got to the following. I have a fragment like this:

```
            fragment on UserConnection  {
                edges @include(if: $cond)  {
                    node { id,
                    }
                }
            }
```

It works when doing just browser rendering but fails as described above (no error but nothing gets rendered) when doing SSR. However, if I move the @include directive one level up and change it to this:

```
            fragment on UserConnection @include(if: $cond)  {
                edges {
                    node { id,
                    }
                }
            }
```

Then it does work, but I'm getting some other warnings (since my fragment now turns empty and some objects relying on it).
I assume the code at the top should work, right? Why would it fail only when doing SSR but not on the browser?

**Comment by denvned** [comment]
@shaimo Have you solved the issue? I didn't have much time recently to investigate what might be wrong here.

**Comment by juhaelee** [comment]
I'm also facing the same issue with the @include directive. However, the @skip directive appears to be working fine

**Comment by denvned** [comment]
@juhaelee Can you share the Relay container definitions containing the fragments with `@include` and `@skip`?

**Comment by juhaelee** [comment]
@denvned looks something like this:

``` javascript
Relay.createContainer(Item, {
   initialVariables: {
       show: false,
   },
   fragments: {
      submission: () => Relay.QL`
         totalCommentCount @include(if: $show) // this doesn't work
         commentCount @skip(if: $show) // this works
      `,
   },
});
```

**Comment by juhaelee** [comment]
hey @denvned so I was able to fix my issue, it was because I wasn't passing down the variables correctly down to my fragments. I did not know that you had to pass the variables as props as well:

See https://github.com/facebook/relay/issues/309#issuecomment-140485321. Passing them down as props solved my issue
