### ISSUE TITLE
Cannot run after cp -rf to new folder

### ISSUE THREAD

**Issue by reactor81** [denvned/isomorphic-relay-router#23]
the example works okay when not moved.. But whenever I do a cp -rf to a new folder, and use a regular npm link to isomorphic-relay-router, npm start gives me an error about babel-node cannot be found (from updateSchema.js).

Any ideas why I cant seem to run this in another folder? I modified package.json to include "isomorphic-relay-router": "0.7.0-beta.0",

**Comment by denvned** [comment]
> babel-node cannot be found

This means _npm_ cannot find _babel-cli_ package in _node_modules_ of the new directory. Probably, you just need to run `npm install` in the new directory.

**Comment by reactor81** [comment]
@denvned   Thanks, I've tried that but I found that it did not work. Hm. I also have babel-cli installed globally. 

The error seems to be from /node_modules/.bin/babel-node   . As you can see.. it does a require("../lib/babel-node");

and that fails since there is no lib folder in node_modules.. Hmm

**Comment by reactor81** [comment]
While doing cp to another folder did not work, checking into github and checkout out again into a folder I wanted does work, so this is resolved now, thanks.
