### ISSUE TITLE
RouterContext is not a valid React Element

### ISSUE THREAD

**Issue by mattecapu** [denvned/isomorphic-relay-router#24]
This is the code I use to pre-render on the server

``` js
const networkLayer = new Relay.DefaultNetworkLayer(
    `http://${HTTP_ADDRESS}:${HTTP_PORT}/graphql`
);

return async (context) => {
    const { redirectLocation, renderProps } =
        await new Promise((resolve, reject) => {
            match({
                routes: routes,
                location: context.request.url
            }, (err, redirectLocation, renderProps) => {
                if (err) {
                    return reject(err);
                }
                return resolve({ redirectLocation, renderProps });
            });
        });

    if (redirectLocation) {
        context.redirect(302, redirectLocation.pathname + redirectLocation.search);
    } else if (renderProps) {
        const { data, props } =
            await IsomorphicRouter.prepareData(renderProps, networkLayer);

        context.response.status = 200;
        context.response.body = DocumentBuilder(
            <IsomorphicRouter.RouterContext {...props} />,
            data
        );
    } else {
        context.throw(404, 'Not found');
    }
};
```

`DocumentBuilder` just renders a template using `ReactDOMServer.renderToStaticMarkup`, which fires the error:

> Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

I'm using `isomorphic-relay-router@0.7.0-beta.0`, `isomorphic-relay@0.6.0-beta.0`, `react-router@2.3.0` and `react-router-relay@0.12.2`.
I suspect the latter in particular could be the cause of the problem, because it had a recent breaking API change to the renderer component, but I really don't know.

**Comment by denvned** [comment]
In v0.7, you need to render `<Router {...props} />` (`Router` is from the _react-router_ package) instead of `<IsomorphicRouter.RouterContext {...props} />`, like [here](https://github.com/denvned/isomorphic-relay-router/blob/v0.7.0-beta.0/examples/todo/src/renderOnServer.js#L26).

**Comment by mattecapu** [comment]
Thank you, I was following the example from the README which isn't updated yet

**Comment by denvned** [comment]
I forgot to update one line of code in the README. Now it is fixed: https://github.com/denvned/isomorphic-relay-router/commit/8894ca5ae050ca04d8b0b1c98c9b38f08958b8bf. Thank you for pointing that out!

**Comment by mattecapu** [comment]
I was going to make a PR for that but you have been quicker! Thank you
