### ISSUE TITLE
npm start is very slow (server.js)

### ISSUE THREAD

**Issue by reactor81** [denvned/isomorphic-relay-router#31]
I find that npm start takes a long time everytime I make a change and need to see it. I changed babel-node to babel in package.json which I think made it a little bit faster, but it is still quite slow. 

Any ideas for how to make faster turn-around for changes? I tried to run webpack --watch but that did nothing.

**Comment by denvned** [comment]
In [isomorphic-relay-boilerplate](https://github.com/denvned/isomorphic-relay-boilerplate) for the client side code I used hot module replacement mechanism provided by webpack. And probably, it can be improved further by using the _babel --watch_ together with _nodeamon_ for the server side code.

**Comment by ramazankaragoz** [comment]
selam gardaşlar

**Comment by Harshaaaa** [comment]
### _**The monsters running wild inside of me am faded**_
