### ISSUE TITLE
Upgrade to react-router v2.4.0 and potentially create a withRelay HOC?

### ISSUE THREAD

**Issue by juhaelee** [denvned/isomorphic-relay-router#32]
React router 2.4.0 introduced a HOC called `withRouter` where router is injected to the props of a react component. I would definitely favor this over reaching into context to get Relay. What do you think @denvned ?

**Comment by denvned** [comment]
It should be already possible to use _react-router_ 2.4.0.

Regarding `withRelay`, I think it might be useful outside _isomorphic-router-relay_, so it is more appropriate to be implemented by Relay itself.
