### ISSUE TITLE
Sub route queries error

### ISSUE THREAD

**Issue by juhaelee** [denvned/isomorphic-relay-router#34]
Part of my route is set up like so:

``` jsx
<Route path=":widgetId" component={Widget} queries={{
   viewer: () => Relay.QL`query { viewer }`,
   widget: () => Relay.QL`query { widget(widgetId: $widgetId) }`
}}>
   <Route
      path="details"
      component={Details}
      queries={{ widget: () => Relay.QL`query { widget(widgetId: $widgetId) }` }}
   />
</Route>
```

Widget has 2 fragments: viewer and widget
Details has 1 fragment: widget

However, I get the following error: 

```
Error:  Invariant Violation: Relay(Details).getFragment(): `viewer` is not a valid fragment name. Available fragments names: `widget``.
```

Is the queries for route `:widgetId` valid? If I remove viewer from the top level route, everything works.

**Comment by denvned** [comment]
There are more details: http://stackoverflow.com/questions/37662913/sub-route-queries-error-for-react-router-relay
Closing as not directly related to _isomorphic-relay-router_. Looks like a user error.
