### ISSUE TITLE
Changing Relay query parameter causes remount of route's component

### ISSUE THREAD

**Issue by juhaelee** [denvned/isomorphic-relay-router#36]
setting a query string such as

``` javascript
<Link to={{...this.props.location, query: { c: "new" } />
```

without having a route change, is re-mounting all the components for that route. Is this a bug?

This is specific to a query that I pass down as a variable using `prepareParams`. If I pass a query that isn't associate with relay, then it acts as expected

**Comment by denvned** [comment]
This question is more suitable for the [react-router](https://github.com/ReactTraining/react-router/issues) repository.
