### ISSUE TITLE
SEO indexing

### ISSUE THREAD

**Issue by hbizira** [denvned/isomorphic-relay-router#41]
Hi, I was curious if the initial server side render that's returned gets indexed by google and bing? I'm attempting to build a site that has each route indexed by search engines and I'm concerned that isomorphic-relay-router's preloaded json data that gets returned to the client will not have a chance to be loaded into the html before the search engine attempts to index the site. Has anyone tested this aspect with google and/or bing?

**Comment by mattecapu** [comment]
JSON data it's only needed to rehydrate components client-side.

If you render your components on the server, then the search engines will see meaningiful HTML alongside a bunch of JSON which would be ignored.

Try to navigate to your page with JS disabled, you'll see just what is rendered on the server (that is pretty much what web crawlers see).

**Comment by hbizira** [comment]
great thank you @mattecapu I think I was confused by the example todo list which came out empty on initial render but that was because it doesn't have a persistent backend to keep the todo list items.
