### ISSUE TITLE
Pass Relay Variables to route component

### ISSUE THREAD

**Issue by mattecapu** [denvned/isomorphic-relay-router#46]
I have something like this

``` jsx
<Router>
    <Route path="/this" component={Component} queries={..} />
    <Route path="/that" component={Component} queries={..} />
</Router>
```

I need to pass different Relay variables to `Component` depending on the route it was rendered on.
If I use an HOC like [this](https://github.com/reactjs/react-router/issues/3707) `react-router-relay` rightfully complains I'm not providing a Relay container.

I could create a Relay container HOC to do the job but it seems overkill (also inelegant).

Any suggestions?

**Comment by denvned** [comment]
You can use [`prepareParmas`](https://github.com/relay-tools/react-router-relay#additional-parameters) to pass additional params to a route .
