### ISSUE TITLE
Injecting Additional Responses

### ISSUE THREAD

**Issue by ChristopherBiscardi** [denvned/isomorphic-relay-router#47]
# Background

Long story short I built a [static site generator](https://github.com/superawesomelabs/leo) on top of iso-relay/router. The generator generates static html pages with embedded iso-relay preload data, which works wonderfully. It also generates a `client.js` and a "static JSON-file API" from the relay responses when generating the html pages. `client.js` uses the preload data on a given html page to initialize iso-relay, which also works wonderfully. `client.js` then implements a custom Network Layer that turns Relay requests into requests to the previously mentioned hashed JSON files.
## client.js

``` javascript
import IsomorphicRelay from 'isomorphic-relay';
import Relay from 'react-relay';
import IsomorphicRouter from 'isomorphic-relay-router';
import {
  Router,
  match,
  browserHistory
} from 'react-router';
import React from 'react';
import ReactDOM, { render } from 'react-dom';
import md5 from 'md5';

import routes from './load-routes';

var myNetworkLayer = {
  sendMutation(mutationRequest) {
    // ...
  },
  sendQueries(queryRequests) {
    console.log('queryRequests', queryRequests);
    return Promise.all(queryRequests.map(
      queryRequest => fetch(`/api/${md5(window.location.pathname)}.json`)
                        .then(response => response.json())
                        .then(result => {
                          console.log('result',result);
                          if(result.errors) {
                                      queryRequest.reject(new Error('Failed to fetch JSON file'));
                                    } else {
                                      IsomorphicRelay.injectPreparedData(environment, result);
//                                      queryRequest.resolve(result[0]);
                                    }
                                  })
    ));
  },
  supports(...options) {
    // ...
  },
};

// Set up Relay Environment
const environment = new Relay.Environment();
environment.injectNetworkLayer(myNetworkLayer);

// Inject Data from DOM (and network?)
const data = JSON.parse(document.getElementById('preloadedData').textContent);
IsomorphicRelay.injectPreparedData(environment, data);

// Client render (optional):
if (typeof document !== 'undefined') {
  console.log('using client render');
  const outlet = document.getElementById('react-mount');

  // use the same routes object as on the server
  match({routes, history: browserHistory}, (error, redirectLocation, renderProps) => {
    IsomorphicRouter.prepareInitialRender(environment, renderProps).then(props => {
      console.log('matched and props', props)
      ReactDOM.render(<Router {...props} />, outlet);
    });
  });
}
```

The compiled static site showing the usage of client.js is [on GitHub](https://github.com/ChristopherBiscardi/christopherbiscardi.github.com/tree/33a6143d39b15dd7f0f38c853040ae67be650081), as well as live at http://www.christopherbiscardi.com/.
## Problem

To reproduce the issue, navigate to http://www.christopherbiscardi.com/, wait for client.js to log `using client render`, then click on the `posts` item in the navigation twice. The first click with successfully make the request for the JSON file _and_ navigate the URL to `/posts/`, but will re-render the homepage instead of the Posts page. The second click will render the Posts page correctly without making an additional request (since Relay already has the appropriate data).

gif showing the reproduction:

![relay-json-api-problem](https://cloud.githubusercontent.com/assets/551247/17859895/41b7aa80-6840-11e6-9709-32806e8a2550.gif)

---

I'm not sure why this is happening and have tried multiple combinations of the following two functions in `sendQueries` to varying success. 

``` javascript
   IsomorphicRelay.injectPreparedData(environment, result);
// queryRequest.resolve(result[0]);
```

The question I have then is how should I inject additional responses to the Relay store from the Network Layer so that iso-relay and iso-router behave appropriately and the proper page is rendered.

**Comment by denvned** [comment]
The problem with your network layer is that Relay waits for query requests to resolve before rendering new route, and your network layer never resolves them (you commented `queryRequest.resolve`)...

And generally, abusing the network layer like this feels very wrong. Instead I recommend you to use the [`onEnter`](https://github.com/reactjs/react-router/blob/v2.7.0/docs/API.md#onenternextstate-replace-callback) hook to fetch and inject data for the new route, this way Relay won't even send queries because the data will be already there.

**Comment by ChristopherBiscardi** [comment]
> The problem with your network layer...

Indeed. The current version was the "least error inducing". Resolving with data was causing different issues.

@denvned 

> And generally, abusing the network layer like this feels very wrong. Instead I recommend you to use the onEnter hook to fetch and inject data for the new route, this way Relay won't even send queries because the data will be already there.

This sounds like a much better approach, except that iso-/relay-router seems to send the request [in the middleware](https://github.com/denvned/isomorphic-relay-router/blob/2c7e31bfb60a5d4034bc2855045fe81b772b1bb7/src/render.js#L6-L14), which fires before `onEnter`.

react-router-relay exports the middleware and expects the user to apply it

``` javascript
...
  <Router
    history={history}
    render={applyRouterMiddleware(useRelay)}
    environment={Relay.Store}
  >
...
```

; whereas iso-relay-router applies the middleware itself and [exports the result](https://github.com/denvned/isomorphic-relay-router/blob/2c7e31bfb60a5d4034bc2855045fe81b772b1bb7/src/render.js#L6). I'm going to experiment in this area (specifically writing middleware that runs before iso-relay's) to see if it yields a solution.

---

Thanks for pointing out that the network-layer was a poor solution. I was too heads-down to see it.

**Comment by denvned** [comment]
> which fires before onEnter

No, I believe you are mistaken, it should fire after `onEnter`. Just don't forget to use `callback`, the third argument of `onEnter`, call it after the data is fetched and injected.

**Comment by ChristopherBiscardi** [comment]
You are absolutely correct, it was my own mistake.

I ended up using `onChange` with a no-path `Route` that wraps all of the application's routes, which works quite nicely as long as one is comfortable blocking rendering instead of rendering loading states.
