### ISSUE TITLE
React Relay Rails - server rendering implementation

### ISSUE THREAD

**Issue by ramusus** [denvned/isomorphic-relay-router#54]
In the project I'm working on we are using [react-on-rails](https://github.com/shakacode/react_on_rails) application. Here is [tutorial with demo](https://github.com/shakacode/react-webpack-rails-tutorial) how to use this application with basic React Rails Redux Webpack stack. It fully supports server rendering. But for my project we need to support Relay and I submitted [PR to tutorial repo](https://github.com/shakacode/react-webpack-rails-tutorial/pull/328) with Relay demo implementation. Right now it doesn't support server rendering and I want to implement it using your application. I did few attempts, but without success. @denvned, can you guide me how to do this?

It's easy to install tutorial demo with Relay support following [these instructions](https://github.com/shakacode/react-webpack-rails-tutorial#basic-demo-setup) and using my repo for 2 step: 

...
2. `git clone -b relay git@github.com:ramusus/react-webpack-rails-tutorial.git`
...

**Comment by denvned** [comment]
I have never used _react-on-rails_, and more than that, I never programmed in Ruby. So, I am not sure how I can help here. If you have any specific issues maybe I could help.

You can also try to ask a question on https://stackoverflow.com under the _isomorphic-relay_ tag. But you also need to ask specific questions there.
