### ISSUE TITLE
Absolute URL for NetworkLayer not working

### ISSUE THREAD

**Issue by mmjd** [denvned/isomorphic-relay-router#56]
in client.js of the todo example, setting an absolute URL to DefaultNetworkLayer will raise 404 error. it still tries to connect to http://localhost:8080/graphql. what is the problem?

**Comment by denvned** [comment]
Are you sure it tries to connect to _localhost_? Can't it be that it actually tries to connect to the host specified by the absolute URL, but the host's [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) settings (or their absence) don't allow connection?

**Comment by mmjd** [comment]
server rendering is done successfully using the same URL at server but when a mutation is applied at client-side, it tries to connect to http://localhost:8000/graphql which is nodejs server but the URL I have configured is http://localhost/8080/myproject/graphql (CORS enabled Java server) and it raises 404. when I inject networkLayer to Relay in addition to environment at client-side, it works as expected.

**Comment by denvned** [comment]
To apply mutations you need to use the `relay` prop passed to your component instead of global `Relay.Store`.

**Comment by mmjd** [comment]
thank you
