### ISSUE TITLE
Update react-router dependency.

### ISSUE THREAD

**Issue by carlrosell** [denvned/isomorphic-relay-router#57]
There is a new (major) release of react-router.
It would be great if someone could update the peerDependency so we get rid of the warning:
```
npm WARN isomorphic-relay-router@0.8.4 requires a peer of react-router@^2.3.0 but none was installed.
```

**Comment by mattecapu** [comment]
Is it me or this isn't published yet to `npm`?

**Comment by carlrosell** [comment]
@mattecapu No, you're right. This isn't published yet.

**Comment by denvned** [comment]
It is published now. Sorry for delay. Was busy moving to another city...

**Comment by aduth** [comment]
Thanks @denvned , but the latest version on npm (0.8.5) still defines `^2.3.0` as peer dependency for `react-router`.

https://registry.npmjs.org/isomorphic-relay-router/-/isomorphic-relay-router-0.8.5.tgz

**Comment by denvned** [comment]
@aduth Thank you for noticing. Fixed.
