### ISSUE TITLE
Update graphql dependency

### ISSUE THREAD

**Issue by mattecapu** [denvned/isomorphic-relay-router#59]
The newest version of GraphQL is `0.8.0`, I can't find any breaking changes between the currently supported versions and the latest.

I'll be happy to submit a PR for this.

**Comment by carlrosell** [comment]
I'm not sure where you found that dependency 🙂. As far as I can see there are no dependencies to `graphql` from this repo. The only dependency that depends on `graphql` is react-relay's dev dependency and 0.9.3 seems to be the latest version.

**Comment by mattecapu** [comment]
ops wrong repo
