### ISSUE TITLE
How to pass 'context' when SSR(Server-side rendering)?

### ISSUE THREAD

**Issue by jonirrings** [denvned/isomorphic-relay-router#62]
As some react components need a function which is passed by context, how to pass the context to the component when SSR?
In your example, route with component is rendered by
`ReactDOMServer.renderToString(IsomorphicRouter.render(props));`

is there any way to pass context?

**Comment by mattecapu** [comment]
How about providing context from the component mounted by the router?

**Comment by minheq** [comment]
I think you can wrap the IsomorphicRouter with a component that contains the context that you want such as: 
`ReactDOMServer.renderToString(<ComponentWithContext>{IsomorphicRouter.render(props)}</ComponentWithContext>);`

**Comment by denvned** [comment]
@minheq's answer is correct.
