### ISSUE TITLE
how to add more middleware?

### ISSUE THREAD

**Issue by gre** [denvned/isomorphic-relay-router#65]
It seems like isomorphic-relay-router hides for us the `render` function passed to Router, however I want to use https://github.com/taion/react-router-scroll react router middleware, is there a way I can use that? Maybe the middleware render should be overridable?

**Comment by benjie** [comment]
From browsing the issues it looks like this was added in #48; and usage is something like:

```es6
import {Router, applyRouterMiddleware} from 'react-router';
import IsomorphicRouter from 'isomorphic-relay-router';
import {useScroll} from 'react-router-scroll';
...
const renderWithMiddleware = applyRouterMiddleware(IsomorphicRouter.useIsoRelay, useScroll());
...
const render = (props) => {
  ReactDOM.render(
    <Router
      {...props}
      render={renderWithMiddleware}
    />
  );
};
```

**Comment by gre** [comment]
oh great! i'll try that
