### ISSUE TITLE
renderFailure not working server side

### ISSUE THREAD

**Issue by khrykin** [denvned/isomorphic-relay-router#7]
Hi! Thanks a lot for your work on isomorphic Relay, really enjoy it!

I'm trying to show `<NotFound />` component when GraphQL server returns "null for non-nullable" error, using `Relay.RootContainer`'s `renderFailure` callback like this:

``` javascript
<Route path="posts/:slug"
      queries={PostQueries}
      component={Post}
      renderFailure={() => <NotFound />}
       />
```

This works well client-side after `<Link to="...">` transitions, while breaking on initial server render, returning:

```
Error: Server request for query `PostQueries` failed for the following reasons:

1. Cannot return null for non-nullable field Query.post.
  query PostQueries{post(slug:"blabla"){id,...__RelayQueryFrag
                    ^^^
```

b/w actually, what I really want is to automatically show `<NotFound />` component on arbitrary route's `renderFailure` both client side and server side.

Any help on this please!

**Comment by denvned** [comment]
Hi! I'm glad you like Isomorphic Relay.

Probably, you can catch `prepareData` error and render the page with empty preloaded data and empty react output:

``` javascript
IsomorphicRouter.prepareData(renderProps).then(render, onError);

function onError(error) {
  res.render(path.resolve('index.ejs', {
    preloadedData: [],
    reactOutput: ''
  });
}
```

In that case the browser will try to run queries itself, receive error, and trigger `renderFailure`, as usual.

**Comment by khrykin** [comment]
That works, thanks a lot!
