### ISSUE TITLE
support babel 6

### ISSUE THREAD

**Issue by cometta** [denvned/isomorphic-relay-router#9]
Please support babel 6

**Comment by cometta** [comment]
node.js hang on line in babel 6. Do let me know if you need to gather debugging info for you to troubleshoot

```
        = ReactDOMServer.renderToString(
            <IsomorphicRouter.RoutingContext {...renderProps} />
        );
```

**Comment by thelordoftheboards** [comment]
@cometta , @denvned I took this project, and couple others as a source and did upgrade to babel 6. If this is of any help, feel free to check out

https://github.com/codefoundries/isomorphic-material-relay-starter-kit

I would like to warn that I am having some issues with the server rendering not matching the client side rendering, and the problem could be in me doing a bad job of converting to babel 6, or something to do with the material-ui library which I am integrating into the project. At this point I am not sure.
Hope this helps.

**Comment by cometta** [comment]
@thelordoftheboards , i tried your repo, when run, i get

[nodemon] starting `./node_modules/.bin/babel-node ./server/server.js`
{ [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
{ [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }

Just wondering did you get hang when executing
`
= ReactDOMServer.renderToString(
            <IsomorphicRouter.RoutingContext {...renderProps} />
        );
`

**Comment by thelordoftheboards** [comment]
I am not sure if you ran `npm run initial-setup`, seems like the .env file is missing. If this does not work please feel free to open an issue.
My project was initially on babel 5 very close to how this repo was structured. When I converted to babel 6 I had some issues with configuring webpack and babel, as well as the relay schema creation, but not with the renderToString. That worked as before.

**Comment by denvned** [comment]
@cometta I plan to update to babel 6, but didn't have time to do it yet.

**Comment by denvned** [comment]
I have just upgraded _isomorphic-relay_ and _isomorphic-relay-router_ including the examples to babel v6.
